create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  usuario text not null unique,
  subscription jsonb not null,
  created_at timestamptz default now()
);
